### ISSUE TITLE
请问有requirements文件吗，我想查看我的版本是否兼容

### ISSUE THREAD

**Issue by RainFo666** [yakhyo/EAST-pt#3]

**Comment by yakhyo** [comment]
Hi @RainFo666 . When I created this repo I did not add requirements (it's been a year almost, but the repo looks like updated last week. actually it's not I just removed the commit history :-) . I am planning to update this repo in this weekend and add new losses.

**Comment by yakhyo** [comment]
@RainFo666, now you can use it. I refactored the repo and provided pretrained weights in `weights` folder and requirements to run the code.
I am closing this issue. If you have any further issues, feel free to reopen the issue again.
